# https://pre-commit.com/
# More hooks available at:
# https://pre-commit.com/hooks.html

# INSTALL ON MAC:
# brew install pre-commit

# INSTALL ON WINDOWS:
# pip install pre-commit

# INSTALL hooks for this workspace
# pre-commit install

repos:
# TERRAFORM
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.74.1
    hooks:
      - id: terraform_fmt
      # - id: terraform_validate
      - id: terraform_tflint
        args:
          - '--args=--only=terraform_deprecated_interpolation'
          - '--args=--only=terraform_deprecated_index'
          - '--args=--only=terraform_unused_declarations'
          - '--args=--only=terraform_comment_syntax'
          - '--args=--only=terraform_documented_outputs'
          - '--args=--only=terraform_documented_variables'
          - '--args=--only=terraform_typed_variables'
          - '--args=--only=terraform_module_pinned_source'
          - '--args=--only=terraform_naming_convention'
          - '--args=--only=terraform_required_version'
          - '--args=--only=terraform_required_providers'
          - '--args=--only=terraform_standard_module_structure'
          - '--args=--only=terraform_workspace_remote'
      # - id: terraform_tfsec
      #  files: ^.*.tf$
      #  args:
      #    - '--args=--config-file=.tfsec-config.yml'
      # - id: terraform_checkov
      #   args: ['--args=--download-external-modules true', '--args=--quiet']
  # BUG: terraform_docs hook conflicts when used more than once.
  # Workaround with Python
  - repo: local
    hooks:
    - id: Terraform docs
      name: Terraform docs
      entry: python3 examples/terraform-docs.py
      language: system
      types: [python]
      always_run: true
      pass_filenames: false
# Python
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
    - id: flake8
# PRECOMMIT - GENERAL
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=1024']
      - id: check-case-conflict
      - id: check-json
        exclude: tsconfig.json|.vscode/extensions.json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: detect-aws-credentials
        args: ['--allow-missing-credentials']
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: no-commit-to-branch
      - id: requirements-txt-fixer
      - id: trailing-whitespace
